import React, { useState, useMemo } from "react";
import { INDUSTRY, CAPITAL, STORAGE, OBSOLESCENCE, RISK,
         computeHolding, defaultsForIndustry, classifyIndustry } from "../lib/holding";
import { GROQ_URL, GROQ_MODEL, GROQ_API_KEY } from "../lib/ai";

/**
 * Five questions → an annual holding rate, with the arithmetic shown.
 *
 * The rate is computed in code from lookup tables, never generated by a model, so the
 * same answers always give the same number. The only AI step is turning free text like
 * "we sell bathroom vanities" into an industry key, and that's cached and constrained to
 * a fixed list — the model never sees or produces a percentage.
 */
export default function HoldingWizard({ lm = false, onApply, onClose }) {
  const [text, setText] = useState("");
  const [industry, setIndustry] = useState("");
  const [how, setHow] = useState(null);
  const [thinking, setThinking] = useState(false);
  const [ownsSpace, setOwnsSpace] = useState(true);
  const [dropship, setDropship] = useState(false);
  const [capital, setCapital] = useState("own_cash");
  const [knownRate, setKnownRate] = useState("");
  const [override, setOverride] = useState({});

  const card = lm ? "bg-white border-slate-200" : "bg-[#0d1117] border-slate-800";
  const text_ = lm ? "text-slate-900" : "text-white";
  const muted = "text-slate-500";
  const inp = lm ? "bg-white border-slate-300 text-slate-900" : "bg-slate-900 border-slate-700 text-slate-200";

  const presets = useMemo(() => defaultsForIndustry(industry || "general", ownsSpace),
                          [industry, ownsSpace]);
  const answers = {
    capital, knownRate, dropship,
    storageBulk: override.storageBulk ?? presets.storageBulk,
    obsolescence: override.obsolescence ?? presets.obsolescence,
    risk: override.risk ?? presets.risk,
  };
  const { holding, breakdown } = computeHolding(answers);

  const identify = async () => {
    if (!text.trim()) return;
    setThinking(true);
    const r = await classifyIndustry(text, { apiKey: GROQ_API_KEY, url: GROQ_URL, model: GROQ_MODEL });
    setIndustry(r.key); setHow(r.how); setThinking(false);
  };

  const Row = ({ label, value, onChange, options }) => (
    <label className="block">
      <span className={`block text-[10px] uppercase tracking-widest font-bold ${muted} mb-1`}>{label}</span>
      <select value={value} onChange={(e) => onChange(e.target.value)}
        className={`w-full rounded-lg border px-2 py-1.5 text-xs ${inp}`}>
        {Object.entries(options).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
      </select>
    </label>
  );

  return (
    <div className={`${card} border rounded-2xl p-4 space-y-4`}>
      <div>
        <h3 className={`text-sm font-bold ${text_}`}>Work out your holding cost</h3>
        <p className={`text-[11px] ${muted} mt-1 leading-relaxed`}>
          Five questions. The rate is calculated from your answers — the same answers always give
          the same number, and you can see every part of it below.
        </p>
      </div>

      <div>
        <span className={`block text-[10px] uppercase tracking-widest font-bold ${muted} mb-1`}>1 · What do you sell?</span>
        <div className="flex gap-2">
          <input value={text} onChange={(e) => setText(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && identify()}
            placeholder="e.g. bathroom vanities and mirrors, sold online"
            className={`flex-1 rounded-lg border px-2 py-1.5 text-xs ${inp}`} />
          <button onClick={identify} disabled={thinking || !text.trim()}
            className="px-3 py-1.5 rounded-lg text-xs font-bold bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white">
            {thinking ? "…" : "Identify"}
          </button>
        </div>
        <select value={industry} onChange={(e) => { setIndustry(e.target.value); setHow("manual"); }}
          className={`mt-2 w-full rounded-lg border px-2 py-1.5 text-xs ${inp}`}>
          <option value="">— or pick your industry —</option>
          {Object.entries(INDUSTRY).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
        </select>
        {industry && (
          <p className={`text-[11px] mt-1 ${muted}`}>
            Using <span className="font-semibold">{INDUSTRY[industry].label}</span>
            {how === "keyword" ? " (matched from your description)"
              : how === "ai" ? " (identified by AI)"
              : how === "cached" ? " (same as last time you typed this)" : ""}
            . It only sets the starting points below — change any of them.
          </p>
        )}
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div>
          <Row label="2 · How is stock paid for?" value={capital} onChange={setCapital} options={CAPITAL} />
          <input value={knownRate} onChange={(e) => setKnownRate(e.target.value)} placeholder="know your rate? e.g. 9"
            className={`mt-1.5 w-full rounded-lg border px-2 py-1 text-[11px] ${inp}`} />
        </div>
        <Row label="3 · Where does it sit?" value={dropship ? "dropship" : answers.storageBulk}
          onChange={(v) => { setDropship(v === "dropship"); if (v !== "dropship") setOverride((o) => ({ ...o, storageBulk: v })); }}
          options={STORAGE} />
        <Row label="4 · Does it go out of date?" value={answers.obsolescence}
          onChange={(v) => setOverride((o) => ({ ...o, obsolescence: v }))} options={OBSOLESCENCE} />
        <Row label="5 · Damage or theft risk?" value={answers.risk}
          onChange={(v) => setOverride((o) => ({ ...o, risk: v }))} options={RISK} />
      </div>

      <div className={`rounded-xl border p-3 ${lm ? "bg-emerald-50 border-emerald-200" : "bg-emerald-950/20 border-emerald-900/40"}`}>
        <div className="flex items-baseline gap-2">
          <span className={`text-2xl font-bold tabular-nums ${lm ? "text-emerald-800" : "text-emerald-300"}`}>{holding}%</span>
          <span className={`text-[11px] ${lm ? "text-emerald-700" : "text-emerald-300/80"}`}>per year, of what each unit cost you</span>
        </div>
        <table className="w-full mt-2">
          <tbody>
            {breakdown.map((b) => (
              <tr key={b.part}>
                <td className={`py-0.5 text-[11px] ${lm ? "text-emerald-800" : "text-emerald-300/90"}`}>{b.part}</td>
                <td className={`py-0.5 text-[11px] ${muted}`}>{b.why}</td>
                <td className={`py-0.5 text-[11px] font-bold tabular-nums text-right ${lm ? "text-emerald-800" : "text-emerald-300"}`}>{b.pct}%</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="flex items-center gap-2">
        <button onClick={() => onApply?.(holding)}
          className="px-4 py-2 rounded-lg text-xs font-bold bg-violet-600 hover:bg-violet-500 text-white">
          Use {holding}%
        </button>
        {onClose && <button onClick={onClose} className={`text-[11px] ${muted} hover:underline`}>Cancel</button>}
      </div>
    </div>
  );
}
